# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e56176ca288469628fe893fe8c30fd560594aee043c2ae46da66181be843b160c31220a7ce09070137ab6562abaa861bfe00b284b33bc284c5e3f37cae822af0

test:
  secret_key_base: a2ecf5667d58d18fb65b35a34755cd6a44924d737db696c68d350afbb70ea648f746e0007bcee1a5576147a5d30645277af244c0a995caa3ed4547c775e2a0d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
